server:
  port: 18083
  
# 可以這樣寫，就會開啟所有endpoints(不包含shutdown)
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 也可以這樣寫，就只會開啟指定的endpoint，因此此處只會再額外開啟/actuator/beans和/actuator/mappings
#management.endpoints.web.exposure.include=beans,mappings

# exclude可以用來關閉某些endpoints
# exclude通常會跟include一起用，就是先include了全部，然後再exclude /actuator/beans這個endpoint
#management.endpoints.web.exposure.exclude=beans
#management.endpoints.web.exposure.include=*

# 如果要開啟/actuator/shutdown，要額外再加這一行
  endpoint:
    shutdown:
      enabled: true
  
spring:
  security:
    user:
      name: admin
#      password: "{noop}12345"
#     bcrypt 密碼: 0000
      password: "{bcrypt}$2a$10$JLBkYF9cXfHhYhjQFz7LbuGxJsAolSchQYS2TaCiwmRcsFgEmWVCq"
      roles: ADMIN,ACTRADMIN